; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define void @test (float %b, ptr %p)  {
; CHECK-LABEL: define void @test(
; CHECK-SAME: float [[B:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x float>, ptr [[P]], align 32
; CHECK-NEXT:    [[A:%.*]] = fptosi <8 x float> [[TMP1]] to <8 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = fptosi float [[B]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], -2
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i32> [[A]], i32 [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <8 x i32> poison, i32 [[TMP4]], i64 7
; CHECK-NEXT:    [[TMP6:%.*]] = sitofp <8 x i32> [[TMP5]] to <8 x float>
; CHECK-NEXT:    store <8 x float> [[TMP6]], ptr [[P]], align 32
; CHECK-NEXT:    ret void
;
  %1 = load <8 x float> , ptr %p
  %2 = bitcast <8 x float> %1 to <8 x i32>
  %3 = bitcast <8 x i32> %2 to <8 x float>
  %a = fptosi <8 x float> %3 to <8 x i32>
  %4 = fptosi float %b to i32
  %5 = add i32 %4, -2
  %6 = extractelement <8 x i32> %a, i32 %5
  %7 = insertelement <8 x i32> poison, i32 %6, i32 7
  %8 = sitofp <8 x i32> %7 to <8 x float>
  store <8 x float> %8, ptr %p
  ret void
}

; PR18600
define i32 @test2(i32 %i) {
; CHECK-LABEL: define i32 @test2(
; CHECK-SAME: i32 [[I:%.*]]) {
; CHECK-NEXT:    [[E:%.*]] = extractelement <4 x i32> <i32 1, i32 0, i32 2, i32 0>, i32 [[I]]
; CHECK-NEXT:    ret i32 [[E]]
;
  %e = extractelement <4 x i32> bitcast (<2 x i64> <i64 1, i64 2> to <4 x i32>), i32 %i
  ret i32 %e

}
